### ISSUE TITLE
Favicon not changing with the icon

### ISSUE THREAD

**Issue by JanKrb** [KrbDevelopment/Articly-Frontend#10]
**Describe the bug**
When changing the logo (top-left top bar), the favicon won't change.

**To Reproduce**
1. Change logo in .env
2. Refresh page
3. Take a look at the top bar logo & favicon

**Expected behavior**
The favicon should change too (or there should be a separate config item for that)

**Screenshots**
![2021-08-29_15-28](https://user-images.githubusercontent.com/39383729/131252024-c92f4fb7-9526-47b5-8784-dccc94b499d6.png)
(See left & top circles)

**Comment by NinoKrb** [comment]
I have written an entry in the [frontend documentation](https://github.com/KrbDevelopment/Articly-Documentation/wiki/Frontend).
