### ISSUE TITLE
@NinoKrb Need implementation crud implementation into https://github.com/KrbDevelopment/Articly-Frontend

### ISSUE THREAD

**Issue by JanKrb** [KrbDevelopment/Articly-Frontend#18]
@NinoKrb Need implementation crud implementation into https://github.com/KrbDevelopment/Articly-Frontend

_Originally posted by @JanKrb in https://github.com/KrbDevelopment/Articly-Backend/issues/13#issuecomment-914518104_

**Comment by NinoKrb** [comment]
Implemented in https://github.com/KrbDevelopment/Articly-Frontend/commit/2ea090ea2eb9dca99e24e1a01218fdcfb400d6df
