### ISSUE TITLE
Fix Searchbar results

### ISSUE THREAD

**Issue by NinoKrb** [KrbDevelopment/Articly-Frontend#6]
**Describe the bug**
The search of the searchbar in the administration area refers only to the current displayed content.

**To Reproduce**
1. Go to 'permission' page
2. Click on the searchbar
3. Search for any Permission that is not displayed
4. See that the result is only from the current content

**Expected behavior**
A clear and complete search function that shows you all possible results

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Google Chrome
 - Version: 92.0.4515.107

**Additional context**
Create a search route to resolve content according to keywords

**Comment by JanKrb** [comment]
Backend part is done. For GET ALL routes, add search with a search keyword (string).
https://github.com/KrbDevelopment/Articly-Backend/commit/eb36bec944dac8cb6b81046636b6cf3a5853c87e
